# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
gripper :   # RH-P12-RN(A)
  ID: 0 
  Return_Delay_Time: 1    # item name : value
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
vertical:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 0
rotary:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 2
  Profile_Acceleration: 0
  Profile_Velocity: 0
